/*
 Navicat Premium Data Transfer

 Source Server         : Aeldra
 Source Server Type    : MySQL
 Source Server Version : 100338
 Source Host           : 192.168.178.140:3306
 Source Schema         : player

 Target Server Type    : MySQL
 Target Server Version : 100338
 File Encoding         : 65001

 Date: 05/07/2023 13:49:32
*/

SET NAMES utf8mb4;
SET FOREIGN_KEY_CHECKS = 0;

-- ----------------------------
-- Table structure for pet
-- ----------------------------
DROP TABLE IF EXISTS `pet`;
CREATE TABLE `pet`  (
  `item_id` int(11) UNSIGNED NOT NULL AUTO_INCREMENT,
  `name` varchar(24) CHARACTER SET latin1 COLLATE latin1_swedish_ci NOT NULL DEFAULT 'NONAME',
  `level` int(11) UNSIGNED NOT NULL DEFAULT 0,
  `exp` int(11) UNSIGNED NOT NULL DEFAULT 0,
  `exp_item` int(11) UNSIGNED NOT NULL DEFAULT 0,
  `attrtype1` int(11) UNSIGNED NOT NULL DEFAULT 0,
  `attrlevel1` int(11) UNSIGNED NOT NULL DEFAULT 0,
  `attrtype2` int(11) UNSIGNED NOT NULL DEFAULT 0,
  `attrlevel2` int(11) UNSIGNED NOT NULL DEFAULT 0,
  `attrtype3` int(11) UNSIGNED NOT NULL DEFAULT 0,
  `attrlevel3` int(11) UNSIGNED NOT NULL DEFAULT 0,
  `skillpower` int(11) UNSIGNED NOT NULL DEFAULT 0,
  PRIMARY KEY (`level`, `item_id`) USING BTREE
) ENGINE = MyISAM AUTO_INCREMENT = 210000003 CHARACTER SET = latin1 COLLATE = latin1_swedish_ci ROW_FORMAT = FIXED;

-- ----------------------------
-- Table structure for pet_attr_proto
-- ----------------------------
DROP TABLE IF EXISTS `pet_attr_proto`;
CREATE TABLE `pet_attr_proto`  (
  `apply_level` int(11) UNSIGNED NOT NULL DEFAULT 0,
  `apply_type` enum('MAX_HP','MAX_SP','CON','INT','STR','DEX','ATT_SPEED','MOV_SPEED','CAST_SPEED','HP_REGEN','SP_REGEN','POISON_PCT','STUN_PCT','SLOW_PCT','CRITICAL_PCT','PENETRATE_PCT','ATTBONUS_HUMAN','ATTBONUS_ANIMAL','ATTBONUS_ORC','ATTBONUS_MILGYO','ATTBONUS_UNDEAD','ATTBONUS_DEVIL','STEAL_HP','STEAL_SP','MANA_BURN_PCT','DAMAGE_SP_RECOVER','BLOCK','DODGE','RESIST_SWORD','RESIST_TWOHAND','RESIST_DAGGER','RESIST_BELL','RESIST_FAN','RESIST_BOW','RESIST_FIRE','RESIST_ELEC','RESIST_MAGIC','RESIST_WIND','REFLECT_MELEE','REFLECT_CURSE','POISON_REDUCE','KILL_SP_RECOVER','EXP_DOUBLE_BONUS','GOLD_DOUBLE_BONUS','ITEM_DROP_BONUS','POTION_BONUS','KILL_HP_RECOVER','IMMUNE_STUN','IMMUNE_SLOW','IMMUNE_FALL','SKILL','BOW_DISTANCE','ATT_GRADE_BONUS','DEF_GRADE_BONUS','MAGIC_ATT_GRADE_BONUS','MAGIC_DEF_GRADE_BONUS','CURSE_PCT','MAX_STAMINA','ATT_BONUS_TO_WARRIOR','ATT_BONUS_TO_ASSASSIN','ATT_BONUS_TO_SURA','ATT_BONUS_TO_SHAMAN','ATT_BONUS_TO_MONSTER','ATT_BONUS','MALL_DEFBONUS','MALL_EXPBONUS','MALL_ITEMBONUS','MALL_GOLDBONUS','MAX_HP_PCT','MAX_SP_PCT','SKILL_DAMAGE_BONUS','NORMAL_HIT_DAMAGE_BONUS','SKILL_DEFEND_BONUS','NORMAL_HIT_DEFEND_BONUS','EXTRACT_HP_PCT','PC_BANG_EXP_BONUS','PC_BANG_DROP_BONUS','RESIST_WARRIOR','RESIST_ASSASSIN','RESIST_SURA','RESIST_SHAMAN','ENERGY','DEF_GRADE','COSTUME_ATTR_BONUS','MAGIC_ATT_BONUS_PER','MELEE_MAGIC_ATT_BONUS_PER','RESIST_ICE','RESIST_EARTH','RESIST_DARK','RESIST_CRITICAL','RESIST_PENETRATE','BLEEDING_PCT','BLEEDING_REDUCE','ATT_BONUS_TO_WOLFMAN','RESIST_WOLFMAN','RESIST_CLAW','ACCEDRAIN_RATE','RESIST_MAGIC_REDUCTION','ENCHANT_ELECT','ENCHANT_FIRE','ENCHANT_ICE','ENCHANT_WIND','ENCHANT_EARTH','ENCHANT_DARK','ATTBONUS_CZ','ATTBONUS_INSECT','ATTBONUS_DESERT','ATTBONUS_SWORD','ATTBONUS_TWOHAND','ATTBONUS_DAGGER','ATTBONUS_BELL','ATTBONUS_FAN','ATTBONUS_BOW','ATTBONUS_CLAW','RESIST_HUMAN','RESIST_MOUNT_FALL','RESIST_FIST','MOUNT','SK_DMG_SAMYEON','SK_DMG_TANHWAN','SK_DMG_PALBANG','SK_DMG_GIGONGCHAM','SK_DMG_GYOKSAN','SK_DMG_GEOMPUNG','SK_DMG_AMSEOP','SK_DMG_GUNGSIN','SK_DMG_CHARYUN','SK_DMG_SANGONG','SK_DMG_YEONSA','SK_DMG_KWANKYEOK','SK_DMG_GIGUNG','SK_DMG_HWAJO','SK_DMG_SWAERYUNG','SK_DMG_YONGKWON','SK_DMG_PABEOB','SK_DMG_MARYUNG','SK_DMG_HWAYEOMPOK','SK_DMG_MAHWAN','SK_DMG_BIPABU','SK_DMG_YONGBI','SK_DMG_PAERYONG','SK_DMG_NOEJEON','SK_DMG_BYEURAK','SK_DMG_CHAIN','SK_DMG_CHAYEOL','SK_DMG_SALPOONG','SK_DMG_GONGDAB','SK_DMG_PASWAE','NORMAL_HIT_DEFEND_BONUS_BOSS_OR_MORE','SK_DEFEND_BONUS_BOSS_OR_MORE','NORMAL_HIT_DAMAGE_BONUS_BOSS_OR_MORE','SK_DMG_BONUS_BOSS_OR_MORE','HIT_BUFF_ENCHANT_FIRE','HIT_BUFF_ENCHANT_ICE','HIT_BUFF_ENCHANT_ELEC','HIT_BUFF_ENCHANT_WIND','HIT_BUFF_ENCHANT_DARK','HIT_BUFF_ENCHANT_EARTH','HIT_BUFF_RESIST_FIRE','HIT_BUFF_RESIST_ICE','HIT_BUFF_RESIST_ELEC','HIT_BUFF_RESIST_WIND','HIT_BUFF_RESIST_DARK','HIT_BUFF_RESIST_EARTH','USE_SK_CHEONGRANG_MOV_SPEED','USE_SK_CHEONGRANG_CASTING_SPEED','USE_SK_CHAYEOL_CRITICAL_PCT','USE_SK_SANGONG_ATT_GRADE_BONUS','USE_SK_GIGUNG_ATT_GRADE_BONUS','USE_SK_JEOKRANG_DEF_BONUS','USE_SK_GWIGEOM_DEF_BONUS','USE_SK_TERROR_ATT_GRADE_BONUS','USE_SK_MUYEONG_ATT_GRADE_BONUS','USE_SK_MANASHILED_CASTING_SPEED','USE_SK_HOSIN_DEF_BONUS','USE_SK_GICHEON_ATT_GRADE_BONUS','USE_SK_JEONGEOP_ATT_GRADE_BONUS','USE_SK_JEUNGRYEOK_DEF_BONUS','USE_SK_GIHYEOL_ATT_GRADE_BONUS','USE_SK_CHUNKEON_CASTING_SPEED','USE_SK_NOEGEOM_ATT_GRADE_BONUS','SK_DURATION_INCREASE_EUNHYUNG','SK_DURATION_INCREASE_GYEONGGONG','SK_DURATION_INCREASE_GEOMKYUNG','SK_DURATION_INCREASE_JEOKRANG','USE_SK_PALBANG_HP_ABSORB','USE_SK_AMSEOP_HP_ABSORB','USE_SK_YEONSA_HP_ABSORB','USE_SK_YONGBI_HP_ABSORB','USE_SK_CHAIN_HP_ABSORB','USE_SK_PASWAE_SP_ABSORB','USE_SK_GIGONGCHAM_STUN','USE_SK_CHARYUN_STUN','USE_SK_PABEOB_STUN','USE_SK_MAHWAN_STUN','USE_SK_GONGDAB_STUN','USE_SK_SAMYEON_STUN','USE_SK_GYOKSAN_KNOCK','USE_SK_SEOMJEON_KNOCK','USE_SK_SWAERYUNG_KNOCK','USE_SK_HWAYEOMPOK_KNOCK','USE_SK_GONGDAB_KNOCK','USE_SK_KWANKYEOK_KNOCK','USE_SK_SAMYEON_NEXT_COOL_DEC_10PER','USE_SK_GEOMPUNG_NEXT_COOL_DEC_10PER','USE_SK_GUNGSIN_NEXT_COOL_DEC_10PER','USE_SK_KWANKYEOK_NEXT_COOL_DEC_10PER','USE_SK_YONGKWON_NEXT_COOL_DEC_10PER','USE_SK_MARYUNG_NEXT_COOL_DEC_10PER','USE_SK_BIPABU_NEXT_COOL_DEC_10PER','USE_SK_NOEJEON_NEXT_COOL_DEC_10PER','USE_SK_SALPOONG_NEXT_COOL_DEC_10PER','USE_SK_PASWAE_NEXT_COOL_DEC_10PER','ATTBONUS_STONE','DMG_HP_RECOVERY','DMG_SP_RECOVERY','ALIGNMENT_DMG_BONUS','NORMAL_DMG_GUARD','MORE_THEN_HP90_DMG_REDUCE','USE_SK_TUSOK_HP_ABSORB','USE_SK_PAERYONG_HP_ABSORB','USE_SK_BYEURAK_HP_ABSORB','FIRST_ATTR_BONUS','SECOND_ATTR_BONUS','THIRD_ATTR_BONUS','FOURTH_ATTR_BONUS','FIFTH_ATTR_BONUS','USE_SK_SAMYEON_NEXT_COOL_DEC_20PER','USE_SK_GEOMPUNG_NEXT_COOL_DEC_20PER','USE_SK_GUNGSIN_NEXT_COOL_DEC_20PER','USE_SK_KWANKYEOK_NEXT_COOL_DEC_20PER','USE_SK_YONGKWON_NEXT_COOL_DEC_20PER','USE_SK_MARYUNG_NEXT_COOL_DEC_20PER','USE_SK_BIPABU_NEXT_COOL_DEC_20PER','USE_SK_NOEJEON_NEXT_COOL_DEC_20PER','USE_SK_SALPOONG_NEXT_COOL_DEC_20PER','USE_SK_PASWAE_NEXT_COOL_DEC_20PER','USE_SK_CHAYEOL_HP_ABSORB','SUNGMA_STR','SUNGMA_HP','SUNGMA_MOVE','SUNGMA_IMMUNE','HIT_PCT','RANDOM','ATTBONUS_PER_HUMAN','ATTBONUS_PER_ANIMAL','ATTBONUS_PER_ORC','ATTBONUS_PER_MILGYO','ATTBONUS_PER_UNDEAD','ATTBONUS_PER_DEVIL','ENCHANT_PER_ELECT','ENCHANT_PER_FIRE','ENCHANT_PER_ICE','ENCHANT_PER_WIND','ENCHANT_PER_EARTH','ENCHANT_PER_DARK','ATTBONUS_PER_CZ','ATTBONUS_PER_INSECT','ATTBONUS_PER_DESERT','ATTBONUS_PER_STONE','ATTBONUS_PER_MONSTER','RESIST_PER_HUMAN','RESIST_PER_ICE','RESIST_PER_DARK','RESIST_PER_EARTH','RESIST_PER_FIRE','RESIST_PER_ELEC','RESIST_PER_MAGIC','RESIST_PER_WIND','HIT_BUFF_SSTR','HIT_BUFF_SMOVE','HIT_BUFF_SHP','HIT_BUFF_SIMN','MOUNT_MELEE_MAGIC_ATT_PER','DISMOUNT_MOVE_SPEED_BONUS_PER','HIT_AUTO_HP_REC','HIT_AUTO_SP_REC','USE_SK_COOL_DEC_ALL','HIT_STONE_ATT','HIT_STONE_DEF','KILL_BOSS_ITEM_BONUS','MOB_HIT_MOB_AGGR','NO_DEATH_AND_HP_REC30','AUTO_PICKUP','MOUNT_NO_KNOCKBACK','SUNGMA_PER_STR','SUNGMA_PER_HP','SUNGMA_PER_MOVE','SUNGMA_PER_IMN','IMN_POISON100','IMN_BLEED100') CHARACTER SET latin1 COLLATE latin1_swedish_ci NOT NULL DEFAULT 'MAX_HP',
  `value` int(11) UNSIGNED NOT NULL DEFAULT 0,
  `refine_id` int(11) UNSIGNED NOT NULL DEFAULT 0,
  `required_pet_level` int(11) UNSIGNED NOT NULL DEFAULT 0,
  PRIMARY KEY (`apply_level`) USING BTREE
) ENGINE = MyISAM CHARACTER SET = latin1 COLLATE = latin1_swedish_ci ROW_FORMAT = FIXED;

-- ----------------------------
-- Table structure for pet_evolve_proto
-- ----------------------------
DROP TABLE IF EXISTS `pet_evolve_proto`;
CREATE TABLE `pet_evolve_proto`  (
  `level` int(11) UNSIGNED NOT NULL DEFAULT 0,
  `name` varchar(24) CHARACTER SET latin1 COLLATE latin1_swedish_ci NOT NULL DEFAULT 'NONAME',
  `refine_id` int(11) UNSIGNED NOT NULL DEFAULT 0,
  `scale` varchar(100) CHARACTER SET latin1 COLLATE latin1_swedish_ci NOT NULL DEFAULT '',
  `normal_skill_count` int(11) UNSIGNED NOT NULL DEFAULT 0,
  `heroic_skill_count` int(11) UNSIGNED NOT NULL DEFAULT 0,
  `skillpower` int(11) UNSIGNED NOT NULL DEFAULT 0,
  `skillpower_rerollable` int(11) UNSIGNED NOT NULL DEFAULT 0,
  PRIMARY KEY (`level`) USING BTREE
) ENGINE = MyISAM CHARACTER SET = latin1 COLLATE = latin1_swedish_ci ROW_FORMAT = FIXED;

-- ----------------------------
-- Table structure for pet_skill
-- ----------------------------
DROP TABLE IF EXISTS `pet_skill`;
CREATE TABLE `pet_skill`  (
  `item_id` int(11) UNSIGNED NOT NULL AUTO_INCREMENT,
  `index` int(11) UNSIGNED NOT NULL DEFAULT 0,
  `vnum` int(11) UNSIGNED NOT NULL DEFAULT 0,
  `level` int(11) UNSIGNED NOT NULL DEFAULT 0,
  PRIMARY KEY (`index`, `item_id`) USING BTREE
) ENGINE = MyISAM AUTO_INCREMENT = 210000003 CHARACTER SET = latin1 COLLATE = latin1_swedish_ci ROW_FORMAT = FIXED;

-- ----------------------------
-- Table structure for pet_skill_proto
-- ----------------------------
DROP TABLE IF EXISTS `pet_skill_proto`;
CREATE TABLE `pet_skill_proto`  (
  `apply` enum('MAX_HP','MAX_SP','CON','INT','STR','DEX','ATT_SPEED','MOV_SPEED','CAST_SPEED','HP_REGEN','SP_REGEN','POISON_PCT','STUN_PCT','SLOW_PCT','CRITICAL_PCT','PENETRATE_PCT','ATTBONUS_HUMAN','ATTBONUS_ANIMAL','ATTBONUS_ORC','ATTBONUS_MILGYO','ATTBONUS_UNDEAD','ATTBONUS_DEVIL','STEAL_HP','STEAL_SP','MANA_BURN_PCT','DAMAGE_SP_RECOVER','BLOCK','DODGE','RESIST_SWORD','RESIST_TWOHAND','RESIST_DAGGER','RESIST_BELL','RESIST_FAN','RESIST_BOW','RESIST_FIRE','RESIST_ELEC','RESIST_MAGIC','RESIST_WIND','REFLECT_MELEE','REFLECT_CURSE','POISON_REDUCE','KILL_SP_RECOVER','EXP_DOUBLE_BONUS','GOLD_DOUBLE_BONUS','ITEM_DROP_BONUS','POTION_BONUS','KILL_HP_RECOVER','IMMUNE_STUN','IMMUNE_SLOW','IMMUNE_FALL','SKILL','BOW_DISTANCE','ATT_GRADE_BONUS','DEF_GRADE_BONUS','MAGIC_ATT_GRADE_BONUS','MAGIC_DEF_GRADE_BONUS','CURSE_PCT','MAX_STAMINA','ATT_BONUS_TO_WARRIOR','ATT_BONUS_TO_ASSASSIN','ATT_BONUS_TO_SURA','ATT_BONUS_TO_SHAMAN','ATT_BONUS_TO_MONSTER','ATT_BONUS','MALL_DEFBONUS','MALL_EXPBONUS','MALL_ITEMBONUS','MALL_GOLDBONUS','MAX_HP_PCT','MAX_SP_PCT','SKILL_DAMAGE_BONUS','NORMAL_HIT_DAMAGE_BONUS','SKILL_DEFEND_BONUS','NORMAL_HIT_DEFEND_BONUS','EXTRACT_HP_PCT','PC_BANG_EXP_BONUS','PC_BANG_DROP_BONUS','RESIST_WARRIOR','RESIST_ASSASSIN','RESIST_SURA','RESIST_SHAMAN','ENERGY','DEF_GRADE','COSTUME_ATTR_BONUS','MAGIC_ATT_BONUS_PER','MELEE_MAGIC_ATT_BONUS_PER','RESIST_ICE','RESIST_EARTH','RESIST_DARK','RESIST_CRITICAL','RESIST_PENETRATE','BLEEDING_PCT','BLEEDING_REDUCE','ATT_BONUS_TO_WOLFMAN','RESIST_WOLFMAN','RESIST_CLAW','ACCEDRAIN_RATE','RESIST_MAGIC_REDUCTION','ENCHANT_ELECT','ENCHANT_FIRE','ENCHANT_ICE','ENCHANT_WIND','ENCHANT_EARTH','ENCHANT_DARK','ATTBONUS_CZ','ATTBONUS_INSECT','ATTBONUS_DESERT','ATTBONUS_SWORD','ATTBONUS_TWOHAND','ATTBONUS_DAGGER','ATTBONUS_BELL','ATTBONUS_FAN','ATTBONUS_BOW','ATTBONUS_CLAW','RESIST_HUMAN','RESIST_MOUNT_FALL','RESIST_FIST','MOUNT','SK_DMG_SAMYEON','SK_DMG_TANHWAN','SK_DMG_PALBANG','SK_DMG_GIGONGCHAM','SK_DMG_GYOKSAN','SK_DMG_GEOMPUNG','SK_DMG_AMSEOP','SK_DMG_GUNGSIN','SK_DMG_CHARYUN','SK_DMG_SANGONG','SK_DMG_YEONSA','SK_DMG_KWANKYEOK','SK_DMG_GIGUNG','SK_DMG_HWAJO','SK_DMG_SWAERYUNG','SK_DMG_YONGKWON','SK_DMG_PABEOB','SK_DMG_MARYUNG','SK_DMG_HWAYEOMPOK','SK_DMG_MAHWAN','SK_DMG_BIPABU','SK_DMG_YONGBI','SK_DMG_PAERYONG','SK_DMG_NOEJEON','SK_DMG_BYEURAK','SK_DMG_CHAIN','SK_DMG_CHAYEOL','SK_DMG_SALPOONG','SK_DMG_GONGDAB','SK_DMG_PASWAE','NORMAL_HIT_DEFEND_BONUS_BOSS_OR_MORE','SK_DEFEND_BONUS_BOSS_OR_MORE','NORMAL_HIT_DAMAGE_BONUS_BOSS_OR_MORE','SK_DMG_BONUS_BOSS_OR_MORE','HIT_BUFF_ENCHANT_FIRE','HIT_BUFF_ENCHANT_ICE','HIT_BUFF_ENCHANT_ELEC','HIT_BUFF_ENCHANT_WIND','HIT_BUFF_ENCHANT_DARK','HIT_BUFF_ENCHANT_EARTH','HIT_BUFF_RESIST_FIRE','HIT_BUFF_RESIST_ICE','HIT_BUFF_RESIST_ELEC','HIT_BUFF_RESIST_WIND','HIT_BUFF_RESIST_DARK','HIT_BUFF_RESIST_EARTH','USE_SK_CHEONGRANG_MOV_SPEED','USE_SK_CHEONGRANG_CASTING_SPEED','USE_SK_CHAYEOL_CRITICAL_PCT','USE_SK_SANGONG_ATT_GRADE_BONUS','USE_SK_GIGUNG_ATT_GRADE_BONUS','USE_SK_JEOKRANG_DEF_BONUS','USE_SK_GWIGEOM_DEF_BONUS','USE_SK_TERROR_ATT_GRADE_BONUS','USE_SK_MUYEONG_ATT_GRADE_BONUS','USE_SK_MANASHILED_CASTING_SPEED','USE_SK_HOSIN_DEF_BONUS','USE_SK_GICHEON_ATT_GRADE_BONUS','USE_SK_JEONGEOP_ATT_GRADE_BONUS','USE_SK_JEUNGRYEOK_DEF_BONUS','USE_SK_GIHYEOL_ATT_GRADE_BONUS','USE_SK_CHUNKEON_CASTING_SPEED','USE_SK_NOEGEOM_ATT_GRADE_BONUS','SK_DURATION_INCREASE_EUNHYUNG','SK_DURATION_INCREASE_GYEONGGONG','SK_DURATION_INCREASE_GEOMKYUNG','SK_DURATION_INCREASE_JEOKRANG','USE_SK_PALBANG_HP_ABSORB','USE_SK_AMSEOP_HP_ABSORB','USE_SK_YEONSA_HP_ABSORB','USE_SK_YONGBI_HP_ABSORB','USE_SK_CHAIN_HP_ABSORB','USE_SK_PASWAE_SP_ABSORB','USE_SK_GIGONGCHAM_STUN','USE_SK_CHARYUN_STUN','USE_SK_PABEOB_STUN','USE_SK_MAHWAN_STUN','USE_SK_GONGDAB_STUN','USE_SK_SAMYEON_STUN','USE_SK_GYOKSAN_KNOCK','USE_SK_SEOMJEON_KNOCK','USE_SK_SWAERYUNG_KNOCK','USE_SK_HWAYEOMPOK_KNOCK','USE_SK_GONGDAB_KNOCK','USE_SK_KWANKYEOK_KNOCK','USE_SK_SAMYEON_NEXT_COOL_DEC_10PER','USE_SK_GEOMPUNG_NEXT_COOL_DEC_10PER','USE_SK_GUNGSIN_NEXT_COOL_DEC_10PER','USE_SK_KWANKYEOK_NEXT_COOL_DEC_10PER','USE_SK_YONGKWON_NEXT_COOL_DEC_10PER','USE_SK_MARYUNG_NEXT_COOL_DEC_10PER','USE_SK_BIPABU_NEXT_COOL_DEC_10PER','USE_SK_NOEJEON_NEXT_COOL_DEC_10PER','USE_SK_SALPOONG_NEXT_COOL_DEC_10PER','USE_SK_PASWAE_NEXT_COOL_DEC_10PER','ATTBONUS_STONE','DMG_HP_RECOVERY','DMG_SP_RECOVERY','ALIGNMENT_DMG_BONUS','NORMAL_DMG_GUARD','MORE_THEN_HP90_DMG_REDUCE','USE_SK_TUSOK_HP_ABSORB','USE_SK_PAERYONG_HP_ABSORB','USE_SK_BYEURAK_HP_ABSORB','FIRST_ATTR_BONUS','SECOND_ATTR_BONUS','THIRD_ATTR_BONUS','FOURTH_ATTR_BONUS','FIFTH_ATTR_BONUS','USE_SK_SAMYEON_NEXT_COOL_DEC_20PER','USE_SK_GEOMPUNG_NEXT_COOL_DEC_20PER','USE_SK_GUNGSIN_NEXT_COOL_DEC_20PER','USE_SK_KWANKYEOK_NEXT_COOL_DEC_20PER','USE_SK_YONGKWON_NEXT_COOL_DEC_20PER','USE_SK_MARYUNG_NEXT_COOL_DEC_20PER','USE_SK_BIPABU_NEXT_COOL_DEC_20PER','USE_SK_NOEJEON_NEXT_COOL_DEC_20PER','USE_SK_SALPOONG_NEXT_COOL_DEC_20PER','USE_SK_PASWAE_NEXT_COOL_DEC_20PER','USE_SK_CHAYEOL_HP_ABSORB','SUNGMA_STR','SUNGMA_HP','SUNGMA_MOVE','SUNGMA_IMMUNE','HIT_PCT','RANDOM','ATTBONUS_PER_HUMAN','ATTBONUS_PER_ANIMAL','ATTBONUS_PER_ORC','ATTBONUS_PER_MILGYO','ATTBONUS_PER_UNDEAD','ATTBONUS_PER_DEVIL','ENCHANT_PER_ELECT','ENCHANT_PER_FIRE','ENCHANT_PER_ICE','ENCHANT_PER_WIND','ENCHANT_PER_EARTH','ENCHANT_PER_DARK','ATTBONUS_PER_CZ','ATTBONUS_PER_INSECT','ATTBONUS_PER_DESERT','ATTBONUS_PER_STONE','ATTBONUS_PER_MONSTER','RESIST_PER_HUMAN','RESIST_PER_ICE','RESIST_PER_DARK','RESIST_PER_EARTH','RESIST_PER_FIRE','RESIST_PER_ELEC','RESIST_PER_MAGIC','RESIST_PER_WIND','HIT_BUFF_SSTR','HIT_BUFF_SMOVE','HIT_BUFF_SHP','HIT_BUFF_SIMN','MOUNT_MELEE_MAGIC_ATT_PER','DISMOUNT_MOVE_SPEED_BONUS_PER','HIT_AUTO_HP_REC','HIT_AUTO_SP_REC','USE_SK_COOL_DEC_ALL','HIT_STONE_ATT','HIT_STONE_DEF','KILL_BOSS_ITEM_BONUS','MOB_HIT_MOB_AGGR','NO_DEATH_AND_HP_REC30','AUTO_PICKUP','MOUNT_NO_KNOCKBACK','SUNGMA_PER_STR','SUNGMA_PER_HP','SUNGMA_PER_MOVE','SUNGMA_PER_IMN','IMN_POISON100','IMN_BLEED100') CHARACTER SET latin1 COLLATE latin1_swedish_ci NOT NULL DEFAULT 'MAX_HP',
  `value` int(11) UNSIGNED NOT NULL DEFAULT 0,
  `is_heroic` int(11) UNSIGNED NOT NULL DEFAULT 0
) ENGINE = MyISAM CHARACTER SET = latin1 COLLATE = latin1_swedish_ci ROW_FORMAT = FIXED;

SET FOREIGN_KEY_CHECKS = 1;
