import random

packets = ['HEADER_CG_ATTACK_TRAP','HEADER_CG_CHAT','HEADER_CG_PLAYER_CREATE','HEADER_CG_PLAYER_DESTROY','HEADER_CG_PLAYER_SELECT','HEADER_CG_CHARACTER_MOVE','HEADER_CG_SYNC_POSITION','HEADER_CG_ENTERGAME','HEADER_CG_ITEM_USE','HEADER_CG_ITEM_DROP','HEADER_CG_ITEM_MOVE','HEADER_CG_ITEM_PICKUP','HEADER_CG_QUICKSLOT_ADD','HEADER_CG_QUICKSLOT_DEL','HEADER_CG_QUICKSLOT_SWAP','HEADER_CG_WHISPER','HEADER_CG_ITEM_DROP2','HEADER_CG_ON_CLICK','HEADER_CG_EXCHANGE','HEADER_CG_SCRIPT_ANSWER','HEADER_CG_QUEST_INPUT_STRING','HEADER_CG_QUEST_CONFIRM','HEADER_CG_SHOP','HEADER_CG_FLY_TARGETING','HEADER_CG_USE_SKILL','HEADER_CG_ADD_FLY_TARGETING','HEADER_CG_SHOOT','HEADER_CG_MYSHOP','HEADER_CG_ITEM_USE_TO_ITEM','HEADER_CG_TARGET','HEADER_CG_WARP','HEADER_CG_SCRIPT_BUTTON','HEADER_CG_MESSENGER','HEADER_CG_MALL_CHECKOUT','HEADER_CG_SAFEBOX_CHECKIN','HEADER_CG_SAFEBOX_CHECKOUT','HEADER_CG_PARTY_INVITE','HEADER_CG_PARTY_INVITE_ANSWER','HEADER_CG_PARTY_REMOVE','HEADER_CG_PARTY_SET_STATE','HEADER_CG_PARTY_USE_SKILL','HEADER_CG_SAFEBOX_ITEM_MOVE','HEADER_CG_PARTY_PARAMETER','HEADER_CG_GUILD','HEADER_CG_ANSWER_MAKE_GUILD','HEADER_CG_FISHING','HEADER_CG_GIVE_ITEM','HEADER_CG_EMPIRE','HEADER_CG_REFINE','HEADER_CG_HACK','HEADER_CG_CHANGE_NAME','HEADER_CG_GUILD_SYMBOL_UPLOAD','HEADER_CG_GUILD_SYMBOL_CRC','HEADER_CG_SCRIPT_SELECT_ITEM','HEADER_CG_ATTACK','HEADER_CG_IPV6_FIX_ENABLE','HEADER_CG_ACCE','HEADER_CG_GUILD_SAFEBOX_OPEN','HEADER_CG_GUILD_SAFEBOX_CHECKIN','HEADER_CG_GUILD_SAFEBOX_CHECKOUT','HEADER_CG_GUILD_SAFEBOX_ITEM_MOVE','HEADER_CG_GUILD_SAFEBOX_GIVE_GOLD','HEADER_CG_GUILD_SAFEBOX_GET_GOLD','HEADER_CG_OFFLINE_SHOP_OPEN','HEADER_CG_OFFLINE_SHOP_TAKE_MONEY','HEADER_CG_OFFLINE_SHOP_CLOSE','HEADER_CG_OFFLINE_SHOP_REQ_ITEM_TAKE','HEADER_CG_OFFLINE_SHOP_REQ_ITEM_INSERT','HEADER_CG_OFFLINE_SHOP_REQ_GOLD_TAKE','HEADER_CG_OFFLINE_SHOP_REQ_CLOSE','HEADER_CG_OFFLINE_SHOP_REQ_REOPEN','HEADER_CG_ITEM_DESTROY','HEADER_CG_DRAGON_SOUL_REFINE','HEADER_CG_TARGET_MONSTER_INFO','HEADER_CG_AUCTION','HEADER_CG_PLAYER_INFORMATION','HEADER_CG_ITEM_MULTI_USE','HEADER_CG_BOT_REPORT_LOG','HEADER_CG_FORCED_REWARP','HEADER_CG_DETACH_SINGLE','HEADER_CG_PLAYER_SELECT_HAIR','HEADER_CG_EVENT_REQUEST_ANSWER','HEADER_CG_COSTUME_BONUS_TRANSFER','HEADER_CG_COMBAT_ZONE_REQUEST_ACTION','HEADER_CG_RUNE_PAGE','HEADER_CG_HIT_SPACEBAR','HEADER_CG_QUEST_TRIGGER','HEADER_CG_SKILL_COLOR','HEADER_CG_WIKI','HEADER_CG_EQUIPMENT_PAGE_ADD','HEADER_CG_EQUIPMENT_PAGE_DELETE','HEADER_CG_EQUIPMENT_PAGE_SELECT','HEADER_CG_MARK_LOGIN','HEADER_CG_MARK_CRCLIST','HEADER_CG_MARK_UPLOAD','HEADER_CG_MARK_IDXLIST','HEADER_CG_LOGIN2','HEADER_CG_LOGIN3',]
packet_numbers = [2,3,4,5,6,7,8,9,10,11,12,13,14,15,16,17,18,19,20,22,23,24,25,26,27,28,29,30,31,32,33,34,35,36,37,38,39,40,41,42,43,44,45,46,47,48,49,50,51,56,57,61,62,63,66,68,70,71,72,73,74,75,76,77,78,79,80,81,82,83,84,85,86,87,88,89,90,91,92,93,94,95,96,97,98,99,100,101,102,103,104,105,52,53,54,55,58,60,]

random.shuffle(packet_numbers)

for file in ['../../game/packet.h','../../client/UserInterface/Packet.h',]:
    with open(file,'r') as r:
        lines = r.readlines()

    line_number = 0
    for line in lines:
        if line.startswith("\tHEADER_CG") or line.startswith('    HEADER_CG'):
            packet_number = 0
            for packet in packets:
                if packet in line and line.split(packet)[1][0] in (' ', "\t", '='):
                    lines[line_number] = "\t%-42s= %u,\n" % (packet, packet_numbers[packet_number])
                packet_number += 1
        line_number += 1

    with open(file,'w') as w:
        w.writelines(lines)
